/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package dsldemo

import spock.lang.Specification

class AppTest extends Specification {
    def "application works"() {

        when:
        App.main('programa_da_noite', '../')

        then:
        noExceptionThrown()
    }
}
